### ISSUE TITLE
WDSL website is not working

### ISSUE THREAD

**Issue by inane** [strongloop/strong-soap#191]
Hi!!

Your example is not working because the website specified is down and it is not working.

Please could it be possible to update the example of your documentation with one alternative? it is very important to know the correct behavior of the module for  one future implementation.

Thank you in advance.

**Comment by dhmlau** [comment]
Hi @inane , thanks for bringing this up to us.  With the services in webservicex.net we use become unavailable, we're still in the process of getting things updated.  The tests in the soap related modules are now fixed, and the next step for us is to get the docs updated.

One of the services we use is:  http://ws.cdyne.com/emailverify/Emailvernotestemail.asmx (https://github.com/strongloop/loopback-connector-soap/blob/master/test/test.js#L20).   Would you like to submit a PR to update the example? 

Ideally, we host our own SOAP services so that we have full control over the availability of the services.
