### ISSUE TITLE
Please add cookie security

### ISSUE THREAD

**Issue by bhoriuchi** [strongloop/strong-soap#38]
Working with the vSphere API which requires cookie security

The following works for me, but it would be a nice enhancement to have CookieSecurity added to the ones supported by the project.

```
export class CookieSecurity {
  constructor (cookie, options) {
    this.cookie = cookie
  }
  addHttpHeaders (headers) {
    headers.Cookie = this.cookie
  }
}
```

**Comment by raymondfeng** [comment]
@bhoriuchi Would you please submit a pull request?

**Comment by bhoriuchi** [comment]
PR Created https://github.com/strongloop/strong-soap/pull/39

**Comment by rashmihunt** [comment]
@bhoriuchi I only merged PR 37 and I noticed that PR 39 was gone. I can't really merge PR 40 since it's not showing up in PR list and also if I do directly to the link #40 I don't see anything to merge. Can you resubmit the PR again or create a new PR and resubmit? Can you please add a test case with the PR? Thanks!

**Comment by rashmihunt** [comment]
@bhoriuchi Thank you for the PR. Can you please include a test case in the PR?

**Comment by bhoriuchi** [comment]
@rashmihunt added

**Comment by dhmlau** [comment]
Fixes via https://github.com/strongloop/strong-soap/pull/44
Closing this ticket.
