### ISSUE TITLE
Issue with complexTypes and XSI extensions if you don't define $xsiType as an object

### ISSUE THREAD

**Issue by spadusa** [strongloop/strong-soap#65]
If I have json like this:
```
let element = {
    someChild: {
        $attributes: {
            $xsiType: '{http://namespace.com}Type'
        }
    }
}
```

The xml generated will not namespace the extension elements correctly. If you instead define the json like this:
```
let element = {
    someChild: {
        $attributes: {
            $xsiType: {
                xmlns: 'http://namespace.com',
                type: 'Type'
            }
        }
    }
}
```

Then the generated xml has the extension nodes namespaced correctly.

I was able to trace this behavior down to xmlHandler.js line 151 as follows:
`let extension = descriptor.refOriginal.typeDescriptor.inheritance[child.type];`

`child` is a string in the first json example I gave, so child.type is undefined and thus the extension doesn't get added.

Thanks,
Andreas

**Comment by rashmihunt** [comment]
@spadusa Upon a closer look at this,  the current code is working as expected. I have changed stock quote example see under project_root\example\stockquote.js to add string type attribute for GetQuote

```
 var requestArgs = {      
      symbol: 'IBM',      
      $attributes: {          
            $xsiType: '{http://www.w3.org/2001/XMLSchema}string'       
     }
 };
```

Which generates the below request envelope. I see the namespace is correct.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ns1:GetQuote xmlns:ns1="http://www.webserviceX.NET/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://www.w3.org/2001/XMLSchema" xsi:type="ns2:string">
      <ns1:symbol>IBM</ns1:symbol>
    </ns1:GetQuote>
  </soap:Body>
</soap:Envelope>
```
I also tried adding the same ‘string’ type attribute for the ‘symbol’ which is defined as a simpleType in the schema and the current code is generating the attribute in the request correctly

```
var requestArgs = {   
     symbol: {     
          $attributes: {       
                $xsiType: '{http://www.w3.org/2001/XMLSchema}string'     
           },     
     $value: 'IBM'   }
 };
```

Request envelope is correct

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ns1:GetQuote xmlns:ns1="http://www.webserviceX.NET/">
      <ns1:symbol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://www.w3.org/2001/XMLSchema" xsi:type="ns2:string">IBM</ns1:symbol>
    </ns1:GetQuote>
  </soap:Body>
</soap:Envelope>
```

If you have a different use case where it doesn’t work like above, please attach a test case and also the WSDL to show the problem. Otherwise, we will be closing this issue noting working as expected.

**Comment by rashmihunt** [comment]
Closing as per my comments above.
