### ISSUE TITLE
Do I need to include a WSDL file?

### ISSUE THREAD

**Issue by Gacnt** [strongloop/strong-soap#83]
I'm trying to recreate this PHP with node
```
$username = 'ADMINISTRATOR';
$password = 'ADMINISTRATOR';
$host = "localhost";
$soapport = 7878;
$command = "server info";
$client = new SoapClient(NULL,
array(
    "location" => "http://$host:$soapport/",
    "uri" => "urn:MaNGOS",
    "style" => SOAP_RPC,
    'login' => $username,
    'password' => $password
));
try {
    $result = $client->executeCommand(new SoapParam($command, "command"));
    echo "Command succeeded! Output:<br />\n";
    echo $result;
}
catch (Exception $e)
{
    echo "Command failed! Reason:<br />\n";
    echo $e->getMessage();
}
```

But I keep on having to pass in a `wsdl` url to `createClient` which returns 405 which this does not use `WSDL` any suggestions?

**Comment by rashmihunt** [comment]
@Gacnt I am not sure I understand 'which this does not use WSDL' ... Every createClient(..) call needs to pass in WSDL URL. Is your WSDL hosted at you web service secured? WSDL is downloaded first internally when createClient() gets invoked. If the web service needs authentication to download/access the WSDL, then, current strong-soap doesn't support passing security information during createClient() operation to download/GET the WSDL except if the security is NTLMSecurity. 

One way you can work around it is to download your WSDL manually and pass in from local file location  instead of remote url.
```
var soap = require('strong-soap').soap;
var url = './stockquote.wsdl';
soap.createClient(url, options, function(err, client) {
       ....
  });
})

```

**Comment by rashmihunt** [comment]
@Gacnt Hope above clarification helped. We will be closing this issue soon.
